// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1) {
  return window['go']['wails']['AgentAPI']['Chat'](arg1);
}

export function Clear() {
  return window['go']['wails']['AgentAPI']['Clear']();
}

export function Emit(arg1) {
  return window['go']['wails']['AgentAPI']['Emit'](arg1);
}

export function ExportText(arg1, arg2) {
  return window['go']['wails']['AgentAPI']['ExportText'](arg1, arg2);
}

export function History() {
  return window['go']['wails']['AgentAPI']['History']();
}

export function Startup(arg1) {
  return window['go']['wails']['AgentAPI']['Startup'](arg1);
}

export function Stop() {
  return window['go']['wails']['AgentAPI']['Stop']();
}
