// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agentservice} from '../models';
import {context} from '../models';

export function Chat(arg1:agentservice.ChatRequest):Promise<agentservice.ChatResponse>;

export function Clear():Promise<void>;

export function Emit(arg1:agentservice.AgentEvent):Promise<void>;

export function ExportText(arg1:string,arg2:string):Promise<string>;

export function History():Promise<agentservice.HistoryResponse>;

export function Startup(arg1:context.Context):Promise<void>;

export function Stop():Promise<void>;
