// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCustomModel(arg1) {
  return window['go']['wails']['ConfigAPI']['DeleteCustomModel'](arg1);
}

export function DeleteFieldEntry(arg1) {
  return window['go']['wails']['ConfigAPI']['DeleteFieldEntry'](arg1);
}

export function DeleteModelGroup(arg1) {
  return window['go']['wails']['ConfigAPI']['DeleteModelGroup'](arg1);
}

export function DeleteTileset(arg1) {
  return window['go']['wails']['ConfigAPI']['DeleteTileset'](arg1);
}

export function GetCurveState() {
  return window['go']['wails']['ConfigAPI']['GetCurveState']();
}

export function GetFlightMetrics() {
  return window['go']['wails']['ConfigAPI']['GetFlightMetrics']();
}

export function GetLlmConfig() {
  return window['go']['wails']['ConfigAPI']['GetLlmConfig']();
}

export function GetSettings() {
  return window['go']['wails']['ConfigAPI']['GetSettings']();
}

export function ListCustomModels() {
  return window['go']['wails']['ConfigAPI']['ListCustomModels']();
}

export function ListFieldEntries() {
  return window['go']['wails']['ConfigAPI']['ListFieldEntries']();
}

export function ListModelGroups() {
  return window['go']['wails']['ConfigAPI']['ListModelGroups']();
}

export function ListTilesets() {
  return window['go']['wails']['ConfigAPI']['ListTilesets']();
}

export function SaveCurveState(arg1) {
  return window['go']['wails']['ConfigAPI']['SaveCurveState'](arg1);
}

export function SaveCustomModel(arg1) {
  return window['go']['wails']['ConfigAPI']['SaveCustomModel'](arg1);
}

export function SaveFieldEntry(arg1) {
  return window['go']['wails']['ConfigAPI']['SaveFieldEntry'](arg1);
}

export function SaveFlightMetrics(arg1) {
  return window['go']['wails']['ConfigAPI']['SaveFlightMetrics'](arg1);
}

export function SaveLlmConfig(arg1) {
  return window['go']['wails']['ConfigAPI']['SaveLlmConfig'](arg1);
}

export function SaveModelGroup(arg1) {
  return window['go']['wails']['ConfigAPI']['SaveModelGroup'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['wails']['ConfigAPI']['SaveSettings'](arg1);
}

export function SaveTileset(arg1) {
  return window['go']['wails']['ConfigAPI']['SaveTileset'](arg1);
}

export function SetCurrentFormat(arg1) {
  return window['go']['wails']['ConfigAPI']['SetCurrentFormat'](arg1);
}
