// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {configservice} from '../models';

export function DeleteCustomModel(arg1:configservice.DeleteCustomModelRequest):Promise<configservice.CustomModelsResponse>;

export function DeleteFieldEntry(arg1:configservice.DeleteFieldEntryRequest):Promise<configservice.FieldEntriesResponse>;

export function DeleteModelGroup(arg1:configservice.DeleteModelGroupRequest):Promise<configservice.ModelGroupsResponse>;

export function DeleteTileset(arg1:configservice.DeleteTilesetRequest):Promise<configservice.TilesetsResponse>;

export function GetCurveState():Promise<configservice.CurveStateResponse>;

export function GetFlightMetrics():Promise<configservice.FlightMetricsResponse>;

export function GetSettings():Promise<configservice.SettingsResponse>;

export function ListCustomModels():Promise<configservice.CustomModelsResponse>;

export function ListFieldEntries():Promise<configservice.FieldEntriesResponse>;

export function ListModelGroups():Promise<configservice.ModelGroupsResponse>;

export function ListTilesets():Promise<configservice.TilesetsResponse>;

export function SaveCurveState(arg1:configservice.CurveStateRequest):Promise<void>;

export function SaveCustomModel(arg1:configservice.CustomModel):Promise<configservice.CustomModelsResponse>;

export function SaveFieldEntry(arg1:configservice.FieldEntry):Promise<configservice.FieldEntriesResponse>;

export function SaveFlightMetrics(arg1:Record<string, any>):Promise<void>;

export function SaveModelGroup(arg1:configservice.ModelGroup):Promise<configservice.ModelGroupsResponse>;

export function SaveSettings(arg1:Record<string, any>):Promise<void>;

export function SaveTileset(arg1:configservice.Tileset):Promise<configservice.TilesetsResponse>;

export function SetCurrentFormat(arg1:string):Promise<void>;
