// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ImportModel(arg1:boolean):Promise<string>;

export function ImportModels(arg1:boolean):Promise<Array<string>>;

export function ImportTileset(arg1:boolean):Promise<string>;

export function PickLogPath():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
