// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportModel(arg1) {
  return window['go']['wails']['HostAPI']['ImportModel'](arg1);
}

export function ImportModels(arg1) {
  return window['go']['wails']['HostAPI']['ImportModels'](arg1);
}

export function ImportTileset(arg1) {
  return window['go']['wails']['HostAPI']['ImportTileset'](arg1);
}

export function PickLogPath() {
  return window['go']['wails']['HostAPI']['PickLogPath']();
}

export function Startup(arg1) {
  return window['go']['wails']['HostAPI']['Startup'](arg1);
}
