// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Browse(arg1) {
  return window['go']['wails']['LogAPI']['Browse'](arg1);
}

export function Commands() {
  return window['go']['wails']['LogAPI']['Commands']();
}

export function CurveData(arg1) {
  return window['go']['wails']['LogAPI']['CurveData'](arg1);
}

export function Errors() {
  return window['go']['wails']['LogAPI']['Errors']();
}

export function Events() {
  return window['go']['wails']['LogAPI']['Events']();
}

export function Fields(arg1) {
  return window['go']['wails']['LogAPI']['Fields'](arg1);
}

export function Load(arg1) {
  return window['go']['wails']['LogAPI']['Load'](arg1);
}

export function LogDefs() {
  return window['go']['wails']['LogAPI']['LogDefs']();
}

export function MAVLinkCommands() {
  return window['go']['wails']['LogAPI']['MAVLinkCommands']();
}

export function MessageTypes() {
  return window['go']['wails']['LogAPI']['MessageTypes']();
}

export function Messages() {
  return window['go']['wails']['LogAPI']['Messages']();
}

export function ModeChanges() {
  return window['go']['wails']['LogAPI']['ModeChanges']();
}

export function Parameters() {
  return window['go']['wails']['LogAPI']['Parameters']();
}

export function Status() {
  return window['go']['wails']['LogAPI']['Status']();
}

export function Summary() {
  return window['go']['wails']['LogAPI']['Summary']();
}

export function TypeBody(arg1) {
  return window['go']['wails']['LogAPI']['TypeBody'](arg1);
}

export function TypeSchema() {
  return window['go']['wails']['LogAPI']['TypeSchema']();
}
