// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logservice} from '../models';
import {parser} from '../models';

export function Browse(arg1:logservice.BrowseRequest):Promise<logservice.BrowseResponse>;

export function Commands():Promise<Array<logservice.CommandEntry>>;

export function CurveData(arg1:logservice.CurveDataRequest):Promise<Array<number>>;

export function Errors():Promise<Array<logservice.ErrorEntry>>;

export function Events():Promise<Array<logservice.EventEntry>>;

export function Fields(arg1:logservice.FieldsRequest):Promise<Array<logservice.FieldInfo>>;

export function Load(arg1:logservice.LoadRequest):Promise<logservice.SummaryResponse>;

export function LogDefs():Promise<logservice.LogDefsResponse>;

export function MAVLinkCommands():Promise<Array<logservice.MAVLinkCommandEntry>>;

export function MessageTypes():Promise<Array<logservice.TypeInfo>>;

export function Messages():Promise<Array<logservice.MessageEntry>>;

export function ModeChanges():Promise<Array<logservice.ModeEntry>>;

export function Parameters():Promise<Array<logservice.Parameter>>;

export function Status():Promise<logservice.StatusResponse>;

export function Summary():Promise<logservice.SummaryResponse>;

export function TypeBody(arg1:logservice.TypeBodyRequest):Promise<Array<number>>;

export function TypeSchema():Promise<Record<string, parser.TypeSchemaEntry>>;
