// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mapservice} from '../models';

export function Available():Promise<boolean>;

export function CacheStats():Promise<mapservice.CacheStatsResponse>;

export function ClearCache():Promise<void>;

export function ClearCacheProvider(arg1:mapservice.ClearCacheProviderRequest):Promise<void>;

export function Providers():Promise<mapservice.ProvidersResponse>;
