// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Available() {
  return window['go']['wails']['MapAPI']['Available']();
}

export function CacheStats() {
  return window['go']['wails']['MapAPI']['CacheStats']();
}

export function ClearCache() {
  return window['go']['wails']['MapAPI']['ClearCache']();
}

export function ClearCacheProvider(arg1) {
  return window['go']['wails']['MapAPI']['ClearCacheProvider'](arg1);
}

export function Providers() {
  return window['go']['wails']['MapAPI']['Providers']();
}
